# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 17, 15, 10, 615867)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 17, 15, 10, 615935)),
        ),
    ]
